version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden-simple
    restart: unless-stopped
    environment:
      # Basic Configuration for Local Development
      DOMAIN: "https://vault.local"
      
      # Admin Configuration
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      
      # Local Development Settings
      SIGNUPS_ALLOWED: true
      INVITATIONS_ALLOWED: true
      SHOW_PASSWORD_HINT: true
      WEB_VAULT_ENABLED: true
      
      # Bitwarden Send Configuration (Secure File Sharing)
      SENDS_ALLOWED: true
      
      # File Upload Configuration
      ATTACHMENT_LIMIT: 104857600      # 100MB per file
      USER_ATTACHMENT_LIMIT: 1073741824  # 1GB total per user
      
      # Security Settings
      EMERGENCY_ACCESS_ALLOWED: true
      PASSWORD_ITERATIONS: 600000
      
      # Logging
      LOG_LEVEL: info
      EXTENDED_LOGGING: true
      
    volumes:
      - vaultwarden_data:/data
    ports:
      - "80:80"
      - "3012:3012"

volumes:
  vaultwarden_data:
    driver: local